version: "3.9"

services:
  graph-postgres:
    image: postgres:14.4
    container_name: graph-postgres
    env_file: ./.env
    volumes:
      - "./graph:/var/lib/postgresql/data"
    ports:
      - "5436:5432"
    networks:
      - auth_common-network

  graph-web:
    build: .
    env_file: .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8006:8000"
    depends_on:
      - graph-postgres
    networks:
      - auth_common-network

networks:
  auth_common-network:
    external: true
